### ISSUE TITLE
Some Suggestions to Add to Menu

### ISSUE THREAD

**Issue by GHUser23** [sneakyevil/SleepingDogs-ModMenu#10]
1) Heat Level Increase / Decrease
-ability to change the heat level at which the police respond to you. Increments or decrements by one with the highest being Heat Level 5.

2) Spawn Bodyguards / Spawn Companion / Make NPC Companion
-In the story, we were able to be paired a few times with AI that would fight alongside us and protect us from enemies. Since this game is based heavily around police role play, would you please add a section under NPC spawning where we can set the ped to be a bodyguard or a companion? IK it's unstable but can you please look into it at least?

Another idea would be to recruit the nearest ped to player as a bodyguard or companion, if possible.

2a) Customization of NPC Companion / Bodyguard
-Things like clothing, weapon, and health would be a few off the top of my head.

3) Send Police Backup
-You have an option to keep the police from chasing you but what if that could be controlled? Or perhaps create a stealth option so that the police AI can't see the player but all other enemy AI can? Then we could do things like spawn police backup to the few gun fight locations in the city or we could even call for them during story missions. Would make the player feel much more like they are a part of the force. You could probably take lots of inspiration from "Year of the Snake".

**Comment by sneakyevil** [comment]
1 & 2) has been added in latest sponsor release: [More Info Here](https://github.com/sneakyevil/SleepingDogs-ModMenu/blob/main/README_sponsor.md).
2a) Weapon & Health has been also added, but clothing is not possible atm.
3) This one is quote not possible besides hardly handling AI by myself there isnt any function that allows me to just send ambient Cops to arrest/attack ped, the heat stuff is hardcoded to be only related to localplayer.
