### ISSUE TITLE
Crash After Spawn npc with AI enabled 

### ISSUE THREAD

**Issue by tupac94400** [sneakyevil/SleepingDogs-ModMenu#12]
hello following your new update, when I make an npc appear with IA activated, once the npc disappears my game crashes systematically, but my game will not crash if I deactivate AI but without IA the ncp do not react it is just statues, so would it be possible to fix the crash after an npc disappears with AI enabled, anyway congratulations for all your hard work 💪🏽

**Comment by sneakyevil** [comment]
It is already mentioned in the description of the option itself that it can cause game to crash and it requires to have AI disabled in order to work. This might get fixed in future after I figure out how I can fix the AI itself.

**Comment by VertofChest** [comment]
Go to the cemetery or island if you want to spawn infinite NPCs
It seems something to do with how the game spawns ambient NPCs that causes the game to crash. if you're in an area with no ambient spawns like the graveyard, you won't crash when spawning stuff
