### ISSUE TITLE
Disable Hud Feature [ingame is broken haha ]

### ISSUE THREAD

**Issue by KabetzuriBoii** [sneakyevil/SleepingDogs-ModMenu#13]

**Comment by sneakyevil** [comment]
Might explaining how it is broken, before I close this? 
Me & friend used that thing multiple times and had no issue with it.

**Comment by KabetzuriBoii** [comment]
> Might explaining how it is broken, before I close this? Me & friend used that thing multiple times and had no issue with it.

its not just me . Most people had this problem . if you play more than 30 minutes without hud - it just crashs . whitescreen ;D . but maybe it is fixed with your mod menue ? who knows . anyways . there are many forums talking about it if you search on google .

**Comment by KabetzuriBoii** [comment]
maybe it can be fixed by you haha ;D .

**Comment by sneakyevil** [comment]
I closing this because I couldn't replicate the issue while having HUD disabled over a hour.
