### ISSUE TITLE
Rain and Time of Day

### ISSUE THREAD

**Issue by Modernaire** [sneakyevil/SleepingDogs-ModMenu#18]
I think currently, triggering rain causes it to move in and last a normal amount of time, after which it stops and the sun comes out again. Can the logic force it to just keep raining as long as the box is checked, forever?

And for time of day options, could a small dialogue box exist that allows manual input? (i.e. you enter 5:20 AM and it locks the time of day to that time, rather than the presets).

Thanks so much.

**Comment by sneakyevil** [comment]
Added in version v1.5.0
https://github.com/sneakyevil/SleepingDogs-ModMenu/releases/tag/v1.5.0
