### ISSUE TITLE
Request : Fix Naz stuck in the beginning fish market chase

### ISSUE THREAD

**Issue by Mrblubb** [sneakyevil/SleepingDogs-ModMenu#20]
In the 1.4 version of the game this bug is NOT present. Only happens after 1.5 and onwards till the latest version. Naz in the prologue gets stuck in the beginning of the fish market chase. So you cannot perform the "Police Takedown" that is meant to be there. Please look into this issue.

**Comment by sneakyevil** [comment]
This is bug in actual game and searching for it will give you result about it on steam forum where they talk about this bug back in 2013 and the solution from one guy is: 

> Just keep running through the door ahaead of Naz and climb over the fence. He will reset.

**Comment by Mrblubb** [comment]
But its not the solution right ? I have the original non-updated game 1.4 and it doesn't happen in it. So if you could somehow look into the files and replace anything from that version into the latest one that might fix it.

**Comment by sneakyevil** [comment]
No
