### ISSUE TITLE
Closes game

### ISSUE THREAD

**Issue by Jacket1000** [sneakyevil/SleepingDogs-ModMenu#21]
I run the game with the executable you linked in case the game crashed on startup and started playing the game.  After about 10 minutes the game just closes. I reload and same thing happens, reloaded again and still the same thing. I'm using the steam version of the Definitive Edition and verified the integrity of the files and it still happens. Any help?

**Comment by sneakyevil** [comment]
Open up explorer and type in the topbar: "%LocalAppData%/CrashDumps" without quotes and there should be ".dmp" files related to sdhdship if there are any sort them by date from newest and upload them somewhere and link me the file so I can take look at why the game crash.

**Comment by Jacket1000** [comment]
[sdhdship.exe.13524.zip](https://github.com/sneakyevil/SleepingDogs-ModMenu/files/11520282/sdhdship.exe.13524.zip)

**Comment by sneakyevil** [comment]
The dump you sent me, points to nothing and has literally no information, do you he perhaps any other file there that is bigger than this one?

**Comment by Jacket1000** [comment]
[sdhdship.exe.908.zip](https://github.com/sneakyevil/SleepingDogs-ModMenu/files/11520583/sdhdship.exe.908.zip)
These maybe...

**Comment by sneakyevil** [comment]
I think I can't get any information from this because your game is installed on different drive then mine. Perhaps you could move the game to C drive? And send me new crash dump when you crash again. The game should be located at the default steam directory: `C:\Program Files (x86)\Steam\steamapps\common\SleepingDogsDefinitiveEdition`

**Comment by Jacket1000** [comment]
Okay mate

**Comment by Jacket1000** [comment]
I moved the game to my C drive and started and crashed at the same spot 2 times but dump files aren't showing up.

**Comment by sneakyevil** [comment]
> I moved the game to my C drive and started and crashed at the same spot 2 times but dump files aren't showing up.

If the game hang out and doesn't instantly crash, you could get ProcessHacker and right click on the game and create dump file manually, but if the game crashes to desktop with no popup then I have no clue what else to do. Perhaps you could tell me what you do in mod menu before the game crashes? If you do nothing and just play I would assume this is not issue mod menu itself.

**Comment by Jacket1000** [comment]
https://mega.nz/file/kL8FiQDR#kEn51_4AagwGhAqiFKnwgn2uf2zCK-WMinJo3nBlRXg
Had to use Mega because the dump file was too large to link.

**Comment by sneakyevil** [comment]
The thing you sent me doesn't identify any crash error or anything. Did you even dump it when the game crashed?

**Comment by Jacket1000** [comment]
My mistake man, here is the newest crash dump
[sdhdship.exe.14052.zip](https://github.com/sneakyevil/SleepingDogs-ModMenu/files/11520851/sdhdship.exe.14052.zip)

**Comment by sneakyevil** [comment]
This is weird, the previous dump u sent has some information, but there was no crash error. And this one you sent shows me same no information as before when you had the game on D: drive. Might you explain what you do in the mod menu itself before it crash perhaps test if the game crash even without mod menu?

**Comment by Jacket1000** [comment]
The game doesn't crash with the mod menu, and I haven't touched any of the settings in the mod menu whenever I loaded.

**Comment by sneakyevil** [comment]
Well I booted it up myself and the game crashed in the tutorial scene perhaps you're also in there. Might try playing first the tutorial scene and then place the mod menu files in game after you're in open world and you're not forced in missions. I gotta take look at this issue later on and also let me know if this also fixed the issue.

**Comment by Jacket1000** [comment]
Alright man, thanks

**Comment by Jacket1000** [comment]
Okay, started new game, got past all of the missions without mod until I unlocked north point apartment and free roam. I left, installed the mod and ran outside for about 5 minutes before the game closed.

**Comment by sneakyevil** [comment]
I know where is the issue, I'll release fix soon.

**Comment by sneakyevil** [comment]
I just released it here: https://github.com/sneakyevil/SleepingDogs-ModMenu/releases/tag/v1.5.3
Lemme know if the game still crashes.

**Comment by Jacket1000** [comment]
Kick ass man! It's working with no issue man. Thank you
