### ISSUE TITLE
[model changer] + [ character animation] breaks game ;D 

### ISSUE THREAD

**Issue by KabetzuriBoii** [sneakyevil/SleepingDogs-ModMenu#24]

**Comment by sneakyevil** [comment]
Might explaining whats the issue and how to reproduce it? If you talking about mission animations that's not possible to fix, certain characters are missing bones that are present on Wei's model.

**Comment by KabetzuriBoii** [comment]
if you change the model - and then try animations it will break the game and you will crash . 
nothing more .

**Comment by sneakyevil** [comment]
Fixed in the latest sponsor release: [More info here](https://github.com/sneakyevil/SleepingDogs-ModMenu/blob/main/README_sponsor.md).
