### ISSUE TITLE
Sponsor release question 

### ISSUE THREAD

**Issue by Jacket1000** [sneakyevil/SleepingDogs-ModMenu#32]
Will the newest file for the sponsor download be eventually added to the current releases for non-sponsors? I just wanted to know if it was like a prerelease or something like that.

**Comment by sneakyevil** [comment]
The sponsors have newer version which later get released to public but not the latest version only the oldest in the sponsor version, this means if there is currently 3 versions in changelog the only oldest will be released to public depending if there is enough sponsors and other factors.
