### ISSUE TITLE
Vertical spawining haha [newest mod menue]

### ISSUE THREAD

**Issue by KabetzuriBoii** [sneakyevil/SleepingDogs-ModMenu#33]
![20230608222941_1](https://github.com/sneakyevil/SleepingDogs-ModMenu/assets/65475288/8f2d3dfa-3e55-46cd-ba36-4f00c50f0f18)

**Comment by KabetzuriBoii** [comment]
whe you load the game, it spawns you like this . and quake is enabled

**Comment by sneakyevil** [comment]
Re-download the latest release, I patched so the Quake Movement isnt enabled by default.
