### ISSUE TITLE
Sleeping Dogs Mod Menu  2012

### ISSUE THREAD

**Issue by forz0i** [sneakyevil/SleepingDogs-ModMenu#36]
Hi Sneakyevil 
Plase add Sleeping Dogs ModMeneu  For orginal game version 2012  Sleeping Dogs 
add change triad model for other model 
thx For all

**Comment by sneakyevil** [comment]
I won't do that because it would be time consuming and even if someone paid me big bucks for doing it, just buy definitive edition on 3rd party site for cheap or buy it on steam for 3$ when its on sale.

**Comment by forz0i** [comment]
Hi sneakyevil

Is it possible in the future? About for me, I will pay you the money.
It is the original favorite version. Never have this much creativity.
Thank you for all that you offer. You are a great team. I have a
simple request. Is it possible to add to the mod? Change all the Triad
gang with other characters in the next version. Amendment with thanks


Le mar. 20 juin 2023 à 04:10, sneakyevil ***@***.***> a
écrit :

**Comment by sneakyevil** [comment]
No, it will not be. I already said that I won't do it even if someone paid me to do it because it is time consuming and not even worth my free time.

**Comment by forz0i** [comment]
I understand your position
Thanks for the above. It's not an easy thing and it takes you time
Is it possible to add to sleeping dogs DE in the next update the
option to change triad by model author option?


Le mar. 20 juin 2023 à 12:22, sneakyevil ***@***.***> a
écrit :
