### ISSUE TITLE
Crashes when I launch

### ISSUE THREAD

**Issue by daNTEEEEEEE** [sneakyevil/SleepingDogs-ModMenu#37]
I have Definitive Edition on Steam and it crashes when I launch no matter what I do I've even replaced the exe with the v1.0 version that you have and it still crashes, any help??

**Comment by sneakyevil** [comment]
Check if you got any crashdumps inside folder `%localappdata%\CrashDumps` from the `sdhdship.exe`. If you got any then upload them on some site and post link here.

**Comment by daNTEEEEEEE** [comment]
> Check if you got any crashdumps inside folder `%localappdata%\CrashDumps` from the `sdhdship.exe`. If you got any then upload them on some site and post link here.

Hello so with the v1.0 exe file there is no crashdump but with the normal steam version i get this crash dump : https://mega.nz/file/fSZBCLyS#KFNMNJUm2wFPoJ0r5ynQkt1mYRVpakHmvfs5m85pqK8

**Comment by daNTEEEEEEE** [comment]
it still crashes either way

**Comment by sneakyevil** [comment]
I need crashdump with the executable that is required for the Mod Menu itself and not newer executable from steam version.

**Comment by daNTEEEEEEE** [comment]
any ideas on how i can fix this??

**Comment by VertofChest** [comment]
My girlfriend got set on fire.

**Comment by sneakyevil** [comment]
Closing this as you didn't provide me any more information and didn't send any crashdump file. Sending crashdump from steam executable that's literally different build doesn't give any hint to fix issue with crash when its literally totally different build and mod menu will try accesses addresses that doesn't even match the newest build.
