### ISSUE TITLE
Request: NPC Spawning

### ISSUE THREAD

**Issue by SergerantJoe** [sneakyevil/SleepingDogs-ModMenu#4]
One of the main things I'd love to see is the ability to spawn friendly NPCs, either from one of the gangs or police/SWAT. 
There's a few missions that give you allies to help in fights and it would be amazing to replicate that in free roam.

**Comment by sneakyevilSK** [comment]
I'll add it in the future.

**Comment by VertofChest** [comment]
Zolika1351 has already added this to his mod menu for Sleeping Dogs, however his menu seems to be broken as it has a bunch of features like unlimited ammo that don't work and keybinds that aren't bound/improperly documented.

**Comment by sneakyevil** [comment]
Added in version 1.4
https://github.com/sneakyevil/SleepingDogs-ModMenu/releases/tag/v1.4
