### ISSUE TITLE
HUD enabling\disabling

### ISSUE THREAD

**Issue by Voimics** [sneakyevil/SleepingDogs-ModMenu#42]
This option also in game options, i know. But a lot of people get crashes when playing with HUD off. Dont know what cause that crashes with standart method of hud disabling, but we need some workaround for it. (maybe constant special hotkey button to on\off  ?) Yes, there is some ""fixes" in steam threads about it, but  these methods don't work for me and for a lot of other people too.. Please, fix it somehow, because it looks like you're the only one who can fix it at all.  And thx a lot for sharing your modmenu (especially for fov option)
*link for steam forum with one of the devs where people discussing about   https://steamcommunity.com/app/307690/discussions/0/619568192680921750/?l=italian

**Comment by sneakyevil** [comment]
I have no idea how to reproduce the crash and I had tried before having hud disabled for straight 2 hours while developing mod menu and the game didn't crash once. I will soon release Render Tweaker modification which have some more option to modify and I can add alternative hud off option.

**Comment by Voimics** [comment]
I understand, fortunately not everyone has this error. If such an option appears in your Tweaker, it will be great! In any case, the problem will either be solved or we will get one step closer to understanding its nature..

**Comment by sneakyevil** [comment]
I just released the render tweaker here: https://github.com/sneakyevil/SleepingDogs-RenderTweaker, there is just basic Hud disabling option so might give that a try.
