### ISSUE TITLE
游戏无法启动，上来就crash

### ISSUE THREAD

**Issue by MawkishTREX** [sneakyevil/SleepingDogs-ModMenu#46]
win11系统。instructions里面的mega链接已经失效
报错代码
Crash detected!

Error: 0xC0000005
Address: SDHDShip.exe + 0x0

RAX: 0x7FF6C1CD65C0
RBX: 0x1C78DB95A20
RCX: 0x7FF6C3E7F740
RDX: 0x1C78DB95A48
RBP: 0xA4BFFFC59
RSP: 0xA4BFFFBD8
RSI: 0x1C78DB58F20
RDI: 0x1E

Call Stack: 
[1] [this] + 0x832F1
[2] ntdll.dll + 0x77A3A
[3] ntdll.dll + 0x1E232
[4] ntdll.dll + 0xA2CFE

**Comment by sneakyevil** [comment]
我不是中国人。
It looks like you're using non-steam version executable.
Please read this: https://github.com/SDmodding/.github/blob/main/profile/README.md

**Comment by sneakyevil** [comment]
I closing this as you didn't repond, if you still have the issue just continue writing in this issue.
