### ISSUE TITLE
Hello Friend

### ISSUE THREAD

**Issue by 2723401541** [sneakyevil/SleepingDogs-ModMenu#5]
My idea is to add your modifier to the function of removing NPC and driving vehicles. This will be the perfect of perfect. Personally, I am willing to do my best to support your work in terms of economy and technology. Hope we can realize this dream together, sincerely say thank you

**Comment by VertofChest** [comment]
> My idea is to add your modifier to the function of removing NPC and driving vehicles. This will be the perfect of perfect. Personally, I am willing to do my best to support your work in terms of economy and technology. Hope we can realize this dream together, sincerely say thank you

Dear @2723401541, you can achieve this result by simply spawning a bunch of vehicles somewhere, then blowing them up. The game does not have a cleanup script for destroyed vehicles, so all blown up cars will simply sit there until you start a mission or reload the game :) Cheers

**Comment by sneakyevil** [comment]
Added in version 1.4
https://github.com/sneakyevil/SleepingDogs-ModMenu/releases/tag/v1.4
