### ISSUE TITLE
Turning off the camera auto follow

### ISSUE THREAD

**Issue by 2ndHouse** [sneakyevil/SleepingDogs-ModMenu#60]
Would it be possible to mod in the ability to turn off the camera auto follow in this game? I find it a little annoying that I can't move the camera freely and it keeps wanting to slowly rotate back behind my character when he's moving. It's also troublesome when reversing in a car. I feel like the game would be much more enjoyable if the camera auto follow was turned off, giving the player complete camera control.

**Comment by sneakyevil** [comment]
It might be done for separate modification rather than mod menu itself. Keep eye on the https://github.com/sneakyevil/SleepingDogs-RenderTweaker I might update it someday with some camera tweaks.

**Comment by sneakyevil** [comment]
Just posting follow up update to this. I just released new version of Render Tweaker that has option to disable some auto center stuff related to vehicle. No idea what issue you had with camera, but playing with keyboard and mouse doesn't auto rotate camera while on foot. If you got any issues with that stuff open issue on the RenderTweaker repo.
