### ISSUE TITLE
Crashes game on startup

### ISSUE THREAD

**Issue by VertofChest** [sneakyevil/SleepingDogs-ModMenu#7]
Hi there, unsure why but this appears to crash the game on startup when I load it with it installed. Any ideas as to why?
I saw you asked another user for their crashdump, so I'll post mine. Super small, here it is: [sdhdship.exe.13820.zip](https://github.com/sneakyevil/SleepingDogs-ModMenu/files/11128210/sdhdship.exe.13820.zip)

Thanks in advance for the help and being an awesome dev!

**Comment by VertofChest** [comment]
Using the provided sdship.exe fixed it for some reason,

**Comment by sneakyevil** [comment]
This is because, the initial release of executable was shipped with debug symbol (which helps a lot to get some modding done) and the newer executables is basically same one but some addresses are on different place.

**Comment by VertofChest** [comment]
> This is because, the initial release of executable was shipped with debug symbol (which helps a lot to get some modding done) and the newer executables is basically same one but some addresses are on different place.

Thank you. However, with this .exe , I can't use the keyboard in the main menu. I used to be able to spam Enter key to get past the intro logos and hit Continue, but now I cannot do that for some reason. Is this at all in conflict with your mod?

**Comment by sneakyevil** [comment]
> > This is because, the initial release of executable was shipped with debug symbol (which helps a lot to get some modding done) and the newer executables is basically same one but some addresses are on different place.
> 
> Thank you. However, with this .exe , I can't use the keyboard in the main menu. I used to be able to spam Enter key to get past the intro logos and hit Continue, but now I cannot do that for some reason. Is this at all in conflict with your mod?

Thanks for info, fixed in latest release:
https://github.com/sneakyevil/SleepingDogs-ModMenu/releases/tag/v1.4.2
