### ISSUE TITLE
Unintentional God Mode

### ISSUE THREAD

**Issue by pierrebournee** [sneakyevil/SleepingDogs-ModMenu#8]
Whenever I have this mod menu installed in my directory, there seems to be god mode automatically activated (yes I double checked to see if i accidentally activated god mode in the mod menu and nope it is always off in it) and I cant find a way to get rid of it.

**Comment by sneakyevil** [comment]
Thanks for report, fixed in latest release: https://github.com/sneakyevil/SleepingDogs-ModMenu/releases/tag/v1.4.1
