### ISSUE TITLE
the game is still crashing even after replacing sdhdship.exe (Steam) it is starting up and crashing. I have downloaded dinput8.dll from net it is make the game work but menu is not opening and sound is not coming

### ISSUE THREAD

**Issue by Avinash3625** [sneakyevil/SleepingDogs-ModMenu#9]

**Comment by Avinash3625** [comment]
it is definitely the dinput8 file that is causing the crash for me. For some reason deleting the dinput is making the game work

**Comment by sneakyevil** [comment]
I don't support cracked game version, buy steam version and replace executable that I provided.

**Comment by Avinash3625** [comment]
Ok thanks for explaining I will buy and try
